[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name         tail
    Path         /logs/app.log
    Parser       json
    Tag          app.logs

[OUTPUT]
    Name         es
    Match        app.logs
    Host         opensearch
    Port         9200
    Index        app-logs
    Logstash_Format On
    Suppress_Type_Name On
